HomeWork3
azhukov2204/PopularLibrariesFromfromLessonNumber2 pull request #2
Opened 2021-08-06 08:06 UTC by azhukov2204

В презентерах вызовы методов репозитория обернул в RxJava

2021-08-09 07:25 UTC, PeterBukhal-sovcombank requested changes
Есть критические замечания. Пока не принимаю.

2021-08-09 07:25 UTC, PeterBukhal-sovcombank commented on app/src/main/java/ru/androidlearning/popularlibrariesfromfromlessonnumber2/fragments/login_details/LoginDetailsPresenter.kt
> +                .subscribeOn(Schedulers.io())
Планировщик потоков нужно передавать в конструкторе, иначе его не заменить из вне.

2021-08-09 07:25 UTC, PeterBukhal-sovcombank commented on app/src/main/java/ru/androidlearning/popularlibrariesfromfromlessonnumber2/fragments/login_details/LoginDetailsPresenter.kt
> +                .subscribe({ login ->
Хорошая практика это выносить обработчики в отдельные методы, это улучшит читаемость и возможность их переиспользовать.

2021-08-09 07:25 UTC, PeterBukhal-sovcombank commented on app/src/main/java/ru/androidlearning/popularlibrariesfromfromlessonnumber2/fragments/login_details/LoginDetailsPresenter.kt
> +            Observable.fromCallable { gitHubUsersRepository.getLoginByUserId(userId) }
:-1: Упущен важный момент про который мы говорили на вебинаре, это отмена цепочки в случае необходимости. В текущем виде этот момент не реализован, нужно использовать Disposable и отменить цепочку как минимум в методе презентера onDestroy.

2021-08-09 07:25 UTC, PeterBukhal-sovcombank commented on app/src/main/java/ru/androidlearning/popularlibrariesfromfromlessonnumber2/fragments/users/presenter/UsersPresenter.kt
> +            .subscribeOn(Schedulers.io())
Планировщик потоков нужно передавать в конструкторе, иначе его не заменить из вне.

2021-08-09 07:25 UTC, PeterBukhal-sovcombank commented on app/src/main/java/ru/androidlearning/popularlibrariesfromfromlessonnumber2/fragments/users/presenter/UsersPresenter.kt
> +        Observable.fromCallable { usersRepository.getUsers() }
:-1: Упущен важный момент про который мы говорили на вебинаре, это отмена цепочки в случае необходимости. В текущем виде этот момент не реализован, нужно использовать Disposable и отменить цепочку как минимум в методе презентера onDestroy.

2021-08-09 07:25 UTC, PeterBukhal-sovcombank commented on app/src/main/java/ru/androidlearning/popularlibrariesfromfromlessonnumber2/model/GitHubUsersRepositoryImpl.kt
> +    override fun getLoginByUserId(userId: Long): String = repositories.first { githubUser -> githubUser.userId == userId }.login
:-1:  Нужно сделать сам репозиторий реактивным, чтобы его методы возвращали `Single` а в презентере уже мы подписывались на него.

2021-08-09 08:47 UTC, azhukov2204 commented on app/src/main/java/ru/androidlearning/popularlibrariesfromfromlessonnumber2/fragments/login_details/LoginDetailsPresenter.kt
> +                .subscribeOn(Schedulers.io())
Исправил

2021-08-09 09:14 UTC, azhukov2204 commented on app/src/main/java/ru/androidlearning/popularlibrariesfromfromlessonnumber2/fragments/login_details/LoginDetailsPresenter.kt
> +            Observable.fromCallable { gitHubUsersRepository.getLoginByUserId(userId) }
Исправил

2021-08-09 09:21 UTC, azhukov2204 commented on app/src/main/java/ru/androidlearning/popularlibrariesfromfromlessonnumber2/fragments/users/presenter/UsersPresenter.kt
> +            .subscribeOn(Schedulers.io())
Исправил

2021-08-09 09:23 UTC, azhukov2204 commented on app/src/main/java/ru/androidlearning/popularlibrariesfromfromlessonnumber2/fragments/login_details/LoginDetailsPresenter.kt
> +                .subscribe({ login ->
Исправил

2021-08-09 09:28 UTC, azhukov2204 commented on app/src/main/java/ru/androidlearning/popularlibrariesfromfromlessonnumber2/fragments/users/presenter/UsersPresenter.kt
> +        Observable.fromCallable { usersRepository.getUsers() }
Исправил

2021-08-09 10:00 UTC, azhukov2204 commented on app/src/main/java/ru/androidlearning/popularlibrariesfromfromlessonnumber2/model/GitHubUsersRepositoryImpl.kt
> +    override fun getLoginByUserId(userId: Long): String = repositories.first { githubUser -> githubUser.userId == userId }.login
Исправил

2021-08-09 10:01 UTC, azhukov2204 commented
Исправил выявленные замечания

2021-08-10 06:28 UTC, PeterBukhal-Geekbrains approved these changes
Отлично, задание выполнено, замечаний нет.

2021-08-10 07:33 UTC, merged